### ISSUE TITLE
ImportError: No module named builtins

### ISSUE THREAD

**Issue by madcaplaughsha** [nerevu/riko#3]
On _from riko import get_path_ results in this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/riko/__init__.py", line 37, in <module>
    from builtins import *
ImportError: No module named builtins
```

**Comment by reubano** [comment]
What version of python do you have? And what command did you use to install?

**Comment by madcaplaughsha** [comment]
Python 2.7.9.

pip install riko[async]

**Comment by reubano** [comment]
Ok... let me try to reproduce.

**Comment by reubano** [comment]
Ok. For some reason, setup tools isn't picking up the `future` [requirement](https://github.com/nerevu/riko/blob/master/setup.py#L68).  Just do `pip install future` and you should be good to go.

**Comment by madcaplaughsha** [comment]
Ahh! Ok, worked.

**Comment by reubano** [comment]
Great... still a bug though. So I need to figure out why the requirement isn't being installed (and also why the travis tests passed :/)
