### ISSUE TITLE
Is speedparser 0.2.0 a hard requirement?

### ISSUE THREAD

**Issue by Hunter-Github** [nerevu/riko#36]
Am getting a few errors installing `riko` in a pristine virtualenv under python 3.4.2 (Debian 8).

Riko version 0.51.0.

```
ValueError: ('Expected version spec in', 'speedparser ~=0.2.0', 'at', ' ~=0.2.0')
```

**Comment by Hunter-Github** [comment]
Extra steps taken before headdesking:

```
sudo apt-get install libxslt1-dev
```

Closing for now until I get a reproducible example.

**Comment by reubano** [comment]
Its not required. Just guessing, but try upgrading pip.

**Comment by Hunter-Github** [comment]
Aye, my fault. Got the setup working now, have pip @ 9.0.1 and setuptools @ 35.0.2.

**Comment by reubano** [comment]
Awesome! What was the issue?

**Comment by Hunter-Github** [comment]
Lack of working `lxml`, I suppose. XSLT headers allowed `lxml` to compile.
