### ISSUE TITLE
Flask incompatibility

### ISSUE THREAD

**Issue by impredicative** [nerevu/riko#44]
riko==0.60.4 requires mezmorize==0.25.0 which requires werkzeug==0.13.

Flask==1.0.2 however requires werkzeug==0.14.1.

I need to use Flask. Ergo, I cannot use riko.

**Comment by reubano** [comment]
That's the problem with pre 1.0 libs unfortunately. I'll update the dependencies when I get a chance. Nice catch!

**Comment by reubano** [comment]
Fixed with 1db1084653b77b94cdda2b6d19df2d95bea432ba
